#! /bin/bash
#
#$Author$
#$Date$
#$HeadURL$
#$Revision$

f=$@
run=(0..6)

if (( $# < 2))
then
    echo "usage: benchmarks.bash <delim> <name1> <name2> ... [nameN]"
    exit 1
fi

for (( i=2; i<=$#; i++ ))
do
    echo "$($i)"
    algorithm.py $($i) 1 >test

    if (( -z $test ))
    then
        echo "warning: skipping bad algorithm $($i)" >&2
    else
        run[0]= $( algorithm.py $($i) 10)
        run[1]= $( algorithm.py $($i) 100)
        run[2]= $( algorithm.py $($i) 250)
        run[3]= $( algorithm.py $($i) 500)
        run[4]= $( algorithm.py $($i) 1000)
        run[5]= $( algorithm.py $($i) 1500)

        echo "$($i) $1 ${run[0]} $1 ${run[1]} $1 ${run[2]} $1 ${run[3]} $1 ${run[4]} $1 ${run[5]}" >&1 
    fi
done

exit 0
