#! /bin/bash
#
#$Author: ee364f04 $
#$Date: 2013-01-10 11:02:23 -0500 (Thu, 10 Jan 2013) $
#$HeadURL: svn+ssh://ece364sv@ecegrid-lnx/home/ecegrid/a/ece364sv/svn/S13/students/ee364f04/Lab01/Script1 $
#$Revision: 47487 $

Num_of_Param=$#
Param_values=$@
echo "The program recieved $Num_of_Param parameters"
echo "The parameters are : "
echo "$Param_Values"
echo "The 2nd parameter is \"$2\""
echo "The 4th parameter is \"$4\""
exit 0
